# -*- coding: utf-8 -*-
"""All Intermediate College of Pakistan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lrQF4KJKWWNZO__LwgCHwSj8AL3V39Ub

# **Data Loading and Overview**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('college 2.csv')

df.head()

df.dtypes

"""# **Data Cleaning**

### **In These Datasets the large number of Null values.I can remove the null values **
"""

df.isnull().sum()

df.dropna(inplace=True)

df['Rating'].unique()

df['Rating']=df['Rating'].replace({'0*':0,'1*':1,'2*':2,'3*':3,'4*':4,'5*':5})

df['Rating'].unique()

df.duplicated().sum()

"""# **Basic Statistics**"""

df.describe()

df['Rating'].value_counts()

df['Rating'].mean()

df['Rating'].median()

df['Rating'].mode()

df['Rating'].std()

"""# **Affiliation Analysis**

### **How many college are affiliated with the university of the punjab**
"""

df[df['Affiliation'].str.contains('University of the Punjab')].shape[0]

"""### **Distribution of College based on their Affiliation with HEC**"""

df['Affiliation'].value_counts()

"""### :**EXAMPLE:How many colleges are Affiliated with BISE Lahore**"""

df[df['Affiliation'].str.contains('BISE Lahore')].shape[0]

"""### **Percentage of college are Affiliated with public and private institutions**"""

df['Sector'].value_counts(normalize=True)

"""# **Program Analysis**

### **Most common study program offered**
"""

df['study program'].value_counts()

"""### **How many colleges offer FSC as a study program**  """

df[df['study program'].str.contains('FSc')].shape[0]

"""###**How many colleges offer FA as a study program**"""

df[df['study program'].str.contains('FA')].shape[0]

"""###**How many college offers both FSc And FA Program**"""

df[df['STUDY PROGRAM'].str.contains('FSc') & df['STUDY PROGRAM'].str.contains('FA')].shape[0]

"""## **How many colleges offer ICs as a study program**"""

df[df['study program'].str.contains('ICS')].shape[0]

"""### **What is the most common study program among Private colleges**"""

df[df['Sector']=='Private']['STUDY PROGRAM'].value_counts().idxmax()

"""### **What is the most common study program among Public colleges**"""

df[df['Sector']=='Public']['STUDY PROGRAM'].value_counts().idxmax()

"""# **Rating Analysis**

### **How I can filter colleges with rating of 4* or higher**
"""

df[df['Rating']>=4]

"""###**What is the Average Rating  of colleges that offer FSC as a study program**"""

df[df['study program'].str.contains('FSC')]['Rating'].mean()

"""###**What is the Average Rating  of colleges that offer FA as a study program**"""

df[df['study program'].str.contains('FA')]['Rating'].mean()

"""###**Average Rating for Private colleges compared to Public colleges**"""

df.groupby('Sector')['Rating'].mean()

"""### **Distribution of Rating using Bar chart**"""

df['Rating'].value_counts().plot(kind='bar')

"""###**Average Rating of colleges by city using a Box plot**"""

sns.boxplot(x='City', y='Rating', data=df)
plt.title('Rating Distribution by City')
plt.xlabel('City')
plt.ylabel('Rating')
plt.xticks(rotation=45, ha='right')  # Rotate x-axis labels for better readability
plt.tight_layout() # Adjust layout to prevent labels from overlapping
plt.show()

"""### **Average Rating of colleges in Faisalabad**"""

df[df['City']=='Faisalabad']['Rating'].mean()

"""###**How many colleges have Rating of 3* or higher and located in Lahore**  """

df[(df['Rating']>=3) & (df['City']=='Lahore')].shape[0]

"""#**Geographical Analysis**

###**Which city have highest Number of colleges**
"""

df['City'].value_counts().idxmax()

"""###**These are Colleges located in Lahore**"""

df[df['City'] == 'Lahore'].value_counts()

"""###**Geographical Distributin of colleges located Across different city**"""

df['City'].value_counts().plot(kind='bar')

"""###**Distribution of colleges based on their Rating in a Lahore**"""

df[df['City']=='Lahore']['Rating'].value_counts().plot(kind='bar')

"""###**Distribution of colleges based on their Rating in a Rawalpindi**"""

df[df['City']=='Rawalpindi']['Rating'].value_counts().plot(kind='bar')

"""#**Insights**

---

**Affiliation Analysis**

Most colleges are affiliated with the University of the Punjab or BISE Lahore.
The majority of colleges are private institutions.

**Program Analysis**

The most common study programs offered are FSc, ICS, and I.Com.
Private colleges mostly offer FSc, while public colleges mostly offer FA.

**Rating Analysis**

The average rating of colleges is around 2.5.
Colleges offering FSc have a higher average rating than those offering FA.
Private colleges have a slightly higher average rating compared to public colleges.
Colleges in Lahore have a higher average rating compared to other cities.

**Geographical Analysis**

Lahore has the highest number of colleges.
The distribution of ratings varies across different city

#**Recommendations**

---

**Rating Difference**

**Reasoning**: You've identified that private colleges have a slightly higher average rating than public colleges and that colleges offering FSc have a higher average rating than those offering FA. These are interesting findings!

**Recommendation**: Explore these differences further. You could conduct
 hypothesis testing (e.g., t-test) to determine if these differences in ratings are statistically significant. Additionally, consider investigating factors that might contribute to these differences, such as faculty qualifications, infrastructure, or student-teacher ratios.

 **Explore City-Wise Program Trends**:

**Reasoning**: You've analyzed the distribution of ratings by city and the popularity of different programs. Combining these insights could be valuable.

**Recommendation**: Analyze program preferences within each city. For example, you can determine the most popular programs in Lahore, Faisalabad, and Rawalpindi. This might reveal regional variations in educational choices.

#**finish**

---



---
"""